import AuthRepository from "../repository/auth.repository.js";
import passwordCrypt from "../utils/generatePwdCrypt.js";
import speakeasy from 'speakeasy';
export default class AuthService {
    auth_repository;
    constructor() {
        this.auth_repository = new AuthRepository();
    }
    async signup(signup) {
        try {
            const generatePwdCrypt = await passwordCrypt(signup.password_hash);
            const signupFormated = {
                email: signup.email.toLowerCase(),
                password_hash: generatePwdCrypt,
                name: signup.name.toLowerCase(),
                role: signup.role?.toLocaleLowerCase()
            };
            const dataSignup = await this.auth_repository.signup(signupFormated);
            if (dataSignup) {
                if (dataSignup.code == 'ER_DUP_ENTRY' || dataSignup.sqlState == 'ER_DUP_ENTRY') {
                    console.error('‚ùå: E-mail cadastrado, tente outro!');
                    return { message: "‚ùå E-mail cadastrado, tente outro!", status: 404 };
                }
            }
            return dataSignup;
        }
        catch (error) {
            console.error('‚ùå Erro interno ao tentar usuario no banco de dados');
            throw error;
        }
    }
    async signin(signin) {
        try {
            const newAuth = {
                email: signin.email.toLowerCase(),
                password: signin.password
            };
            const signinService = await this.auth_repository.signin(newAuth);
            if (!signinService) {
                console.error('‚ùå Error: Usu√°rio n√£o encontrado!');
                return signinService;
            }
            if (signinService.email !== newAuth.email) {
                console.error('üö® Usu√°rio ou Senha inv√°lido!');
                return signinService;
            }
            // Retorna o usu√°rio autenticado
            return { data: signinService };
        }
        catch (error) {
            console.error('‚ùå:' + error);
            return error;
        }
    }
    async saveRefreshToken(authId, refreshToken, userAgent, rawIp, proxyIp) {
        try {
            const refreshData = await this.auth_repository.saveRefreshToken(authId, refreshToken, userAgent, rawIp, proxyIp);
            console.log(refreshData);
            return refreshData;
        }
        catch (error) {
            console.error('‚ùå: ' + error);
            return error;
        }
    }
    async logout(refreshToken, authId) {
        try {
            const result = await this.auth_repository.logout(refreshToken, authId);
            return result;
        }
        catch (error) {
            console.error('‚ùå: ' + error);
            return error;
        }
    }
    async enable2fa(secret, qrcode, auth_id) {
        try {
            if (!secret || !qrcode) {
                return { message: '‚ùå Falha ao gerar c√≥digo de verifica√ß√£o!' };
            }
            await this.auth_repository.enable2fa(secret, auth_id); // üîÅ removi qrcode aqui, pois geralmente n√£o √© salvo
            return { message: '‚úÖ 2FA habilitado com sucesso' };
        }
        catch (error) {
            console.error('‚ùå', error);
            return { message: 'Erro interno ao ativar 2FA' };
        }
    }
    async verify2fa(auth_id, entered_code) {
        const secret = await this.auth_repository.verify2fa(auth_id);
        if (!secret) {
            return { message: '‚ùå C√≥digo 2FA inv√°lido ou expirado!', valid: false };
        }
        const isEnteredCodeValid = speakeasy.totp.verify({
            secret,
            encoding: 'base32',
            token: entered_code,
            window: 1
        });
        // // variavel que pega o token digitado pelo usu√°rio
        // const testPostaman = speakeasy.totp({
        //     secret: secret,
        //     encoding: 'base32'
        // })
        console.log("O token √© valido? " + isEnteredCodeValid);
        if (!isEnteredCodeValid) {
            return { message: '‚ùå C√≥digo 2FA inv√°lido ou expirado!', valid: false };
        }
        return { message: '‚úÖ Autentica√ß√£o 2FA validada com sucesso!', valid: true };
    }
    async disable2fa(auth_id) {
        try {
            const updated = await this.auth_repository.disable2fa(auth_id);
            console.log(updated);
            return updated;
        }
        catch (error) {
            console.error("Erro no service (disable2fa):", error);
            throw new Error("Erro ao desativar 2FA no servi√ßo");
        }
    }
}
